name: Auto Run and Commit Every 25 Minutes

on:
  schedule:
    - cron: '*/25 * * * *' # Every 25 minutes
  workflow_dispatch: # Allow manual trigger

jobs:
  auto-run-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Run your script or commands
      - name: Run your script
        run: |
          echo "Running scheduled task at $(date)"
          # Add your custom script here, e.g., Python script or shell commands
          # Example: python script.py

      # Step 3: Commit and push changes
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated commit at $(date)"
          git push
