name: Maintain GitHub longlegs

on:
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Git config
      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"

      # Step 3: Make changes to README.md
      - name: Update README
        run: |
          echo "Last updated on: $(date)" >> README.md

      # Step 4: Commit and push changes
      - name: Commit and push changes
        run: |
          git add README.md
          git commit -m "Automated update: $(date)"
          git push
