name: Commit Changes Every 15 Minutes

on:
  schedule:
    - cron: "*/15 * * * *" # Runs every 15 minutes

jobs:
  commit-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make Changes
        run: |
          echo "Updated at $(date)" >> updates.log

      - name: Configure Git
        run: |
          git config user.name "Your GitHub Username"
          git config user.email "your-email@example.com"

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Auto-update: $(date)" || echo "Nothing to commit"

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
