name: Daily Contributions Every 15 Minutes

on:
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 minutes
  workflow_dispatch: # Allow manual triggering

jobs:
  contribute:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Git configuration
      - name: Set up Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"

      # Step 3: Update the log file
      - name: Update Log File
        run: |
          # Append the current timestamp to log.txt
          echo "Last updated: $(date)" >> log.txt

      # Step 4: Check if there are changes to commit
      - name: Commit Changes
        run: |
          git add log.txt
          if [[ $(git status --porcelain) ]]; then
            git commit -m "Automated update at $(date)"
          fi

      # Step 5: Push the changes to the repository
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
